# Generated by Django 4.2 on 2026-02-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_helprequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay Order ID', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay Payment ID', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, help_text='Razorpay Payment Signature', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_address',
            field=models.CharField(blank=True, help_text='UPI ID or phone number used for payment', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'UPI (Manual)'), ('phone', 'Phone Number (Manual)')], default='razorpay', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Order Created'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=10),
        ),
    ]
