# Generated by Django 4.2 on 2026-04-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='request_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('academic', 'Academic'), ('non_academic', 'Non-Academic')], default='personal', max_length=15),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='target_year',
            field=models.CharField(choices=[('all', 'All Years'), ('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year / Postgrad')], default='all', help_text='Which year is this request for?', max_length=5),
        ),
    ]
