# Generated by Django 4.2 on 2026-04-24 15:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_helprequest_request_type_helprequest_target_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
