# Generated by Django 4.2 on 2026-02-24 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, help_text='e.g. Student, Faculty, Research Assistant, Lab Instructor...', max_length=150)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills', max_length=300)),
                ('year', models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year / Postgrad'), ('alumni', 'Alumni')], max_length=10)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('avatar_color', models.CharField(default='#6C63FF', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
