# Generated by Django 4.2 on 2026-02-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Your phone number for payments', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Your UPI ID (e.g. name@upi)', max_length=100),
        ),
    ]
